num1=int(input("enter the value1"))
num2=int(input("enter the value2"))
add=num1+num2
sub=num1-num2
mul=num1*num2
div=num1/num2
mod=num1%num2
square=num1**2
floor=num1//num2
print("add=",add)
print("sub=",sub)
print("mul=",mul)
print("div=",div)
print("mod=",mod)
print("square=",square)
print("floor=",floor)
